#ifndef LIBPDFRECUT_GLOBAL_H
#define LIBPDFRECUT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBPDFRECUT_LIBRARY)
#  define LIBPDFRECUTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LIBPDFRECUTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBPDFRECUT_GLOBAL_H
